namespace _2015147463_PER.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PriceAdded13 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Administrativo", "VentaID", "dbo.Venta");
            DropForeignKey("dbo.Encomienda", "Bus_BusID", "dbo.Bus");
            DropForeignKey("dbo.Evento", "TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.Evento", "VentaID", "dbo.Venta");
            DropIndex("dbo.Evento", new[] { "VentaID" });
            DropIndex("dbo.Evento", new[] { "TransporteID" });
            DropIndex("dbo.Administrativo", new[] { "VentaID" });
            AddColumn("dbo.Administrativo", "Venta_VentaID", c => c.Int());
            AddColumn("dbo.Administrativo", "Venta_VentaID1", c => c.Int());
            AddColumn("dbo.Empleado", "DNI", c => c.String());
            AddColumn("dbo.Empleado", "LaborSocial", c => c.String());
            AddColumn("dbo.Venta", "ClienteID", c => c.Int(nullable: false));
            AddColumn("dbo.Venta", "AdministrativoID", c => c.Int(nullable: false));
            AddColumn("dbo.Venta", "TipoComprobanteID", c => c.Int(nullable: false));
            AddColumn("dbo.Venta", "TipoPagoID", c => c.Int(nullable: false));
            AddColumn("dbo.Venta", "ServicioID", c => c.Int(nullable: false));
            AddColumn("dbo.Venta", "costo", c => c.Double(nullable: false));
            AddColumn("dbo.Venta", "Observacion", c => c.String());
            AddColumn("dbo.Venta", "Administrativo_EmpleadoID", c => c.Int());
            AddColumn("dbo.Venta", "Cliente_ClienteID", c => c.Int());
            AddColumn("dbo.Venta", "Servicio_ServicioID", c => c.Int());
            AddColumn("dbo.Venta", "TipoComprobante_TipoComprobanteID", c => c.Int());
            AddColumn("dbo.Venta", "TipoPago_TipoPagoID", c => c.Int());
            AddColumn("dbo.Encomienda", "LugarViajeID", c => c.Int(nullable: false));
            AddColumn("dbo.Encomienda", "Beneficiario", c => c.String());
            AddColumn("dbo.Encomienda", "Tarea", c => c.String());
            AddColumn("dbo.Encomienda", "BusID", c => c.Int(nullable: false));
            AddColumn("dbo.Encomienda", "Bust_BusID", c => c.Int());
            AddColumn("dbo.Encomienda", "LugarViaje_LugarViajeID", c => c.Int());
            AddColumn("dbo.Encomienda", "Bus_BusID1", c => c.Int());
            AddColumn("dbo.Transporte", "LugarViajeID", c => c.Int(nullable: false));
            AddColumn("dbo.Transporte", "TipoViajeID", c => c.Int(nullable: false));
            AddColumn("dbo.Transporte", "ClienteID", c => c.Int(nullable: false));
            AddColumn("dbo.Transporte", "Bus_BusID", c => c.Int());
            AddColumn("dbo.Transporte", "Bus2_BusID", c => c.Int());
            AddColumn("dbo.Transporte", "Cliente_ClienteID", c => c.Int());
            AddColumn("dbo.Transporte", "LugarViaje_LugarViajeID", c => c.Int());
            AddColumn("dbo.Transporte", "TipoViaje_TipoViajeID", c => c.Int());
            AddColumn("dbo.Tripulacion", "Nombre", c => c.String());
            AddColumn("dbo.Tripulacion", "Apellido", c => c.String());
            AddColumn("dbo.Tripulacion", "Bus1_BusID", c => c.Int());
            AddColumn("dbo.Tripulacion", "TipoTripulacion_TipoTripulacionID", c => c.Int());
            AddColumn("dbo.Evento", "Transporte_TransporteID", c => c.Int());
            AddColumn("dbo.Evento", "Transporte_TransporteID1", c => c.Int());
            AddColumn("dbo.Evento", "Venta_VentaID", c => c.Int());
            AddColumn("dbo.Evento", "Venta_VentaID1", c => c.Int());
            AddColumn("dbo.LugarViaje", "TipoLugarID", c => c.Int(nullable: false));
            AddColumn("dbo.LugarViaje", "Descripcion", c => c.String());
            AddColumn("dbo.LugarViaje", "TiempoEstimado", c => c.String());
            AddColumn("dbo.LugarViaje", "TransporteID", c => c.Int(nullable: false));
            AddColumn("dbo.LugarViaje", "EncomiendaID", c => c.Int(nullable: false));
            AddColumn("dbo.LugarViaje", "Encomienda_EncomiendaID", c => c.Int());
            AddColumn("dbo.LugarViaje", "TipoLugar_TipoLugarID", c => c.Int());
            AddColumn("dbo.LugarViaje", "Transporte_TransporteID", c => c.Int());
            AddColumn("dbo.LugarViaje", "Encomienda_EncomiendaID1", c => c.Int());
            AddColumn("dbo.LugarViaje", "Transporte_TransporteID1", c => c.Int());
            AddColumn("dbo.Servicio", "Tipo", c => c.String());
            AddColumn("dbo.Servicio", "DescripcionServicio", c => c.String());
            AddColumn("dbo.Servicio", "cantidad", c => c.Int(nullable: false));
            AddColumn("dbo.Servicio", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.Servicio", "Venta_VentaID", c => c.Int());
            AddColumn("dbo.Servicio", "Venta_VentaID1", c => c.Int());
            AddColumn("dbo.TipoComprobante", "Total", c => c.Double(nullable: false));
            AddColumn("dbo.TipoComprobante", "Fecha", c => c.DateTime(nullable: false));
            AddColumn("dbo.TipoComprobante", "Hora", c => c.DateTime(nullable: false));
            AddColumn("dbo.TipoComprobante", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoComprobante", "Venta_VentaID", c => c.Int());
            AddColumn("dbo.TipoComprobante", "Venta_VentaID1", c => c.Int());
            AddColumn("dbo.TipoLugar", "CostoAdicional", c => c.Double(nullable: false));
            AddColumn("dbo.TipoLugar", "LugarViajeID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoLugar", "LugarViaje_LugarViajeID", c => c.Int());
            AddColumn("dbo.TipoLugar", "LugarViaje_LugarViajeID1", c => c.Int());
            AddColumn("dbo.TipoTripulacion", "Descripción", c => c.String());
            AddColumn("dbo.TipoTripulacion", "TripulacionID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoTripulacion", "Tripulacion_TripulacionID", c => c.Int());
            AddColumn("dbo.TipoTripulacion", "Tripulacion_TripulacionID1", c => c.Int());
            AddColumn("dbo.TipoViaje", "Descripcion", c => c.String());
            AddColumn("dbo.TipoViaje", "Beneficio", c => c.String());
            AddColumn("dbo.TipoViaje", "TransporteID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoViaje", "Transporte_TransporteID", c => c.Int());
            AddColumn("dbo.TipoViaje", "Transporte_TransporteID1", c => c.Int());
            AddColumn("dbo.TipoPago", "NombreTipoPago", c => c.String());
            AddColumn("dbo.TipoPago", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoPago", "Venta_VentaID", c => c.Int());
            AddColumn("dbo.TipoPago", "Venta_VentaID1", c => c.Int());
            CreateIndex("dbo.Venta", "Administrativo_EmpleadoID");
            CreateIndex("dbo.Venta", "Cliente_ClienteID");
            CreateIndex("dbo.Venta", "Servicio_ServicioID");
            CreateIndex("dbo.Venta", "TipoComprobante_TipoComprobanteID");
            CreateIndex("dbo.Venta", "TipoPago_TipoPagoID");
            CreateIndex("dbo.Evento", "Transporte_TransporteID");
            CreateIndex("dbo.Evento", "Transporte_TransporteID1");
            CreateIndex("dbo.Evento", "Venta_VentaID");
            CreateIndex("dbo.Evento", "Venta_VentaID1");
            CreateIndex("dbo.Transporte", "Bus_BusID");
            CreateIndex("dbo.Transporte", "Bus2_BusID");
            CreateIndex("dbo.Transporte", "Cliente_ClienteID");
            CreateIndex("dbo.Transporte", "LugarViaje_LugarViajeID");
            CreateIndex("dbo.Transporte", "TipoViaje_TipoViajeID");
            CreateIndex("dbo.Encomienda", "Bust_BusID");
            CreateIndex("dbo.Encomienda", "LugarViaje_LugarViajeID");
            CreateIndex("dbo.Encomienda", "Bus_BusID1");
            CreateIndex("dbo.LugarViaje", "Encomienda_EncomiendaID");
            CreateIndex("dbo.LugarViaje", "TipoLugar_TipoLugarID");
            CreateIndex("dbo.LugarViaje", "Transporte_TransporteID");
            CreateIndex("dbo.LugarViaje", "Encomienda_EncomiendaID1");
            CreateIndex("dbo.LugarViaje", "Transporte_TransporteID1");
            CreateIndex("dbo.TipoLugar", "LugarViaje_LugarViajeID");
            CreateIndex("dbo.TipoLugar", "LugarViaje_LugarViajeID1");
            CreateIndex("dbo.Tripulacion", "Bus1_BusID");
            CreateIndex("dbo.Tripulacion", "TipoTripulacion_TipoTripulacionID");
            CreateIndex("dbo.TipoTripulacion", "Tripulacion_TripulacionID");
            CreateIndex("dbo.TipoTripulacion", "Tripulacion_TripulacionID1");
            CreateIndex("dbo.TipoViaje", "Transporte_TransporteID");
            CreateIndex("dbo.TipoViaje", "Transporte_TransporteID1");
            CreateIndex("dbo.Servicio", "Venta_VentaID");
            CreateIndex("dbo.Servicio", "Venta_VentaID1");
            CreateIndex("dbo.TipoComprobante", "Venta_VentaID");
            CreateIndex("dbo.TipoComprobante", "Venta_VentaID1");
            CreateIndex("dbo.TipoPago", "Venta_VentaID");
            CreateIndex("dbo.TipoPago", "Venta_VentaID1");
            CreateIndex("dbo.Administrativo", "Venta_VentaID");
            CreateIndex("dbo.Administrativo", "Venta_VentaID1");
            AddForeignKey("dbo.Venta", "Administrativo_EmpleadoID", "dbo.Administrativo", "EmpleadoID");
            AddForeignKey("dbo.Encomienda", "Bus_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Encomienda", "Bust_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.LugarViaje", "Encomienda_EncomiendaID", "dbo.Encomienda", "EncomiendaID");
            AddForeignKey("dbo.TipoLugar", "LugarViaje_LugarViajeID", "dbo.LugarViaje", "LugarViajeID");
            AddForeignKey("dbo.LugarViaje", "TipoLugar_TipoLugarID", "dbo.TipoLugar", "TipoLugarID");
            AddForeignKey("dbo.TipoLugar", "LugarViaje_LugarViajeID1", "dbo.LugarViaje", "LugarViajeID");
            AddForeignKey("dbo.LugarViaje", "Transporte_TransporteID", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.Encomienda", "LugarViaje_LugarViajeID", "dbo.LugarViaje", "LugarViajeID");
            AddForeignKey("dbo.LugarViaje", "Encomienda_EncomiendaID1", "dbo.Encomienda", "EncomiendaID");
            AddForeignKey("dbo.Tripulacion", "Bus1_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.TipoTripulacion", "Tripulacion_TripulacionID", "dbo.Tripulacion", "TripulacionID");
            AddForeignKey("dbo.Tripulacion", "TipoTripulacion_TipoTripulacionID", "dbo.TipoTripulacion", "TipoTripulacionID");
            AddForeignKey("dbo.TipoTripulacion", "Tripulacion_TripulacionID1", "dbo.Tripulacion", "TripulacionID");
            AddForeignKey("dbo.Transporte", "Bus_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Transporte", "Bus2_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Transporte", "Cliente_ClienteID", "dbo.Evento", "ClienteID");
            AddForeignKey("dbo.Evento", "Transporte_TransporteID", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.Transporte", "LugarViaje_LugarViajeID", "dbo.LugarViaje", "LugarViajeID");
            AddForeignKey("dbo.LugarViaje", "Transporte_TransporteID1", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.TipoViaje", "Transporte_TransporteID", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.Transporte", "TipoViaje_TipoViajeID", "dbo.TipoViaje", "TipoViajeID");
            AddForeignKey("dbo.TipoViaje", "Transporte_TransporteID1", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.Venta", "Cliente_ClienteID", "dbo.Evento", "ClienteID");
            AddForeignKey("dbo.Evento", "Venta_VentaID1", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Servicio", "Venta_VentaID", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Venta", "Servicio_ServicioID", "dbo.Servicio", "ServicioID");
            AddForeignKey("dbo.Servicio", "Venta_VentaID1", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.TipoComprobante", "Venta_VentaID", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Venta", "TipoComprobante_TipoComprobanteID", "dbo.TipoComprobante", "TipoComprobanteID");
            AddForeignKey("dbo.TipoComprobante", "Venta_VentaID1", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.TipoPago", "Venta_VentaID", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Venta", "TipoPago_TipoPagoID", "dbo.TipoPago", "TipoPagoID");
            AddForeignKey("dbo.TipoPago", "Venta_VentaID1", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Administrativo", "Venta_VentaID", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Administrativo", "Venta_VentaID1", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Encomienda", "Bus_BusID1", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Evento", "Transporte_TransporteID1", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.Evento", "Venta_VentaID", "dbo.Venta", "VentaID");
        }
        
        public override void Down()
        {
            DropForeignKey("dbo.Evento", "Venta_VentaID", "dbo.Venta");
            DropForeignKey("dbo.Evento", "Transporte_TransporteID1", "dbo.Transporte");
            DropForeignKey("dbo.Encomienda", "Bus_BusID1", "dbo.Bus");
            DropForeignKey("dbo.Administrativo", "Venta_VentaID1", "dbo.Venta");
            DropForeignKey("dbo.Administrativo", "Venta_VentaID", "dbo.Venta");
            DropForeignKey("dbo.TipoPago", "Venta_VentaID1", "dbo.Venta");
            DropForeignKey("dbo.Venta", "TipoPago_TipoPagoID", "dbo.TipoPago");
            DropForeignKey("dbo.TipoPago", "Venta_VentaID", "dbo.Venta");
            DropForeignKey("dbo.TipoComprobante", "Venta_VentaID1", "dbo.Venta");
            DropForeignKey("dbo.Venta", "TipoComprobante_TipoComprobanteID", "dbo.TipoComprobante");
            DropForeignKey("dbo.TipoComprobante", "Venta_VentaID", "dbo.Venta");
            DropForeignKey("dbo.Servicio", "Venta_VentaID1", "dbo.Venta");
            DropForeignKey("dbo.Venta", "Servicio_ServicioID", "dbo.Servicio");
            DropForeignKey("dbo.Servicio", "Venta_VentaID", "dbo.Venta");
            DropForeignKey("dbo.Evento", "Venta_VentaID1", "dbo.Venta");
            DropForeignKey("dbo.Venta", "Cliente_ClienteID", "dbo.Evento");
            DropForeignKey("dbo.TipoViaje", "Transporte_TransporteID1", "dbo.Transporte");
            DropForeignKey("dbo.Transporte", "TipoViaje_TipoViajeID", "dbo.TipoViaje");
            DropForeignKey("dbo.TipoViaje", "Transporte_TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.LugarViaje", "Transporte_TransporteID1", "dbo.Transporte");
            DropForeignKey("dbo.Transporte", "LugarViaje_LugarViajeID", "dbo.LugarViaje");
            DropForeignKey("dbo.Evento", "Transporte_TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.Transporte", "Cliente_ClienteID", "dbo.Evento");
            DropForeignKey("dbo.Transporte", "Bus2_BusID", "dbo.Bus");
            DropForeignKey("dbo.Transporte", "Bus_BusID", "dbo.Bus");
            DropForeignKey("dbo.TipoTripulacion", "Tripulacion_TripulacionID1", "dbo.Tripulacion");
            DropForeignKey("dbo.Tripulacion", "TipoTripulacion_TipoTripulacionID", "dbo.TipoTripulacion");
            DropForeignKey("dbo.TipoTripulacion", "Tripulacion_TripulacionID", "dbo.Tripulacion");
            DropForeignKey("dbo.Tripulacion", "Bus1_BusID", "dbo.Bus");
            DropForeignKey("dbo.LugarViaje", "Encomienda_EncomiendaID1", "dbo.Encomienda");
            DropForeignKey("dbo.Encomienda", "LugarViaje_LugarViajeID", "dbo.LugarViaje");
            DropForeignKey("dbo.LugarViaje", "Transporte_TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.TipoLugar", "LugarViaje_LugarViajeID1", "dbo.LugarViaje");
            DropForeignKey("dbo.LugarViaje", "TipoLugar_TipoLugarID", "dbo.TipoLugar");
            DropForeignKey("dbo.TipoLugar", "LugarViaje_LugarViajeID", "dbo.LugarViaje");
            DropForeignKey("dbo.LugarViaje", "Encomienda_EncomiendaID", "dbo.Encomienda");
            DropForeignKey("dbo.Encomienda", "Bust_BusID", "dbo.Bus");
            DropForeignKey("dbo.Encomienda", "Bus_BusID", "dbo.Bus");
            DropForeignKey("dbo.Venta", "Administrativo_EmpleadoID", "dbo.Administrativo");
            DropIndex("dbo.Administrativo", new[] { "Venta_VentaID1" });
            DropIndex("dbo.Administrativo", new[] { "Venta_VentaID" });
            DropIndex("dbo.TipoPago", new[] { "Venta_VentaID1" });
            DropIndex("dbo.TipoPago", new[] { "Venta_VentaID" });
            DropIndex("dbo.TipoComprobante", new[] { "Venta_VentaID1" });
            DropIndex("dbo.TipoComprobante", new[] { "Venta_VentaID" });
            DropIndex("dbo.Servicio", new[] { "Venta_VentaID1" });
            DropIndex("dbo.Servicio", new[] { "Venta_VentaID" });
            DropIndex("dbo.TipoViaje", new[] { "Transporte_TransporteID1" });
            DropIndex("dbo.TipoViaje", new[] { "Transporte_TransporteID" });
            DropIndex("dbo.TipoTripulacion", new[] { "Tripulacion_TripulacionID1" });
            DropIndex("dbo.TipoTripulacion", new[] { "Tripulacion_TripulacionID" });
            DropIndex("dbo.Tripulacion", new[] { "TipoTripulacion_TipoTripulacionID" });
            DropIndex("dbo.Tripulacion", new[] { "Bus1_BusID" });
            DropIndex("dbo.TipoLugar", new[] { "LugarViaje_LugarViajeID1" });
            DropIndex("dbo.TipoLugar", new[] { "LugarViaje_LugarViajeID" });
            DropIndex("dbo.LugarViaje", new[] { "Transporte_TransporteID1" });
            DropIndex("dbo.LugarViaje", new[] { "Encomienda_EncomiendaID1" });
            DropIndex("dbo.LugarViaje", new[] { "Transporte_TransporteID" });
            DropIndex("dbo.LugarViaje", new[] { "TipoLugar_TipoLugarID" });
            DropIndex("dbo.LugarViaje", new[] { "Encomienda_EncomiendaID" });
            DropIndex("dbo.Encomienda", new[] { "Bus_BusID1" });
            DropIndex("dbo.Encomienda", new[] { "LugarViaje_LugarViajeID" });
            DropIndex("dbo.Encomienda", new[] { "Bust_BusID" });
            DropIndex("dbo.Transporte", new[] { "TipoViaje_TipoViajeID" });
            DropIndex("dbo.Transporte", new[] { "LugarViaje_LugarViajeID" });
            DropIndex("dbo.Transporte", new[] { "Cliente_ClienteID" });
            DropIndex("dbo.Transporte", new[] { "Bus2_BusID" });
            DropIndex("dbo.Transporte", new[] { "Bus_BusID" });
            DropIndex("dbo.Evento", new[] { "Venta_VentaID1" });
            DropIndex("dbo.Evento", new[] { "Venta_VentaID" });
            DropIndex("dbo.Evento", new[] { "Transporte_TransporteID1" });
            DropIndex("dbo.Evento", new[] { "Transporte_TransporteID" });
            DropIndex("dbo.Venta", new[] { "TipoPago_TipoPagoID" });
            DropIndex("dbo.Venta", new[] { "TipoComprobante_TipoComprobanteID" });
            DropIndex("dbo.Venta", new[] { "Servicio_ServicioID" });
            DropIndex("dbo.Venta", new[] { "Cliente_ClienteID" });
            DropIndex("dbo.Venta", new[] { "Administrativo_EmpleadoID" });
            DropColumn("dbo.TipoPago", "Venta_VentaID1");
            DropColumn("dbo.TipoPago", "Venta_VentaID");
            DropColumn("dbo.TipoPago", "VentaID");
            DropColumn("dbo.TipoPago", "NombreTipoPago");
            DropColumn("dbo.TipoViaje", "Transporte_TransporteID1");
            DropColumn("dbo.TipoViaje", "Transporte_TransporteID");
            DropColumn("dbo.TipoViaje", "TransporteID");
            DropColumn("dbo.TipoViaje", "Beneficio");
            DropColumn("dbo.TipoViaje", "Descripcion");
            DropColumn("dbo.TipoTripulacion", "Tripulacion_TripulacionID1");
            DropColumn("dbo.TipoTripulacion", "Tripulacion_TripulacionID");
            DropColumn("dbo.TipoTripulacion", "TripulacionID");
            DropColumn("dbo.TipoTripulacion", "Descripción");
            DropColumn("dbo.TipoLugar", "LugarViaje_LugarViajeID1");
            DropColumn("dbo.TipoLugar", "LugarViaje_LugarViajeID");
            DropColumn("dbo.TipoLugar", "LugarViajeID");
            DropColumn("dbo.TipoLugar", "CostoAdicional");
            DropColumn("dbo.TipoComprobante", "Venta_VentaID1");
            DropColumn("dbo.TipoComprobante", "Venta_VentaID");
            DropColumn("dbo.TipoComprobante", "VentaID");
            DropColumn("dbo.TipoComprobante", "Hora");
            DropColumn("dbo.TipoComprobante", "Fecha");
            DropColumn("dbo.TipoComprobante", "Total");
            DropColumn("dbo.Servicio", "Venta_VentaID1");
            DropColumn("dbo.Servicio", "Venta_VentaID");
            DropColumn("dbo.Servicio", "VentaID");
            DropColumn("dbo.Servicio", "cantidad");
            DropColumn("dbo.Servicio", "DescripcionServicio");
            DropColumn("dbo.Servicio", "Tipo");
            DropColumn("dbo.LugarViaje", "Transporte_TransporteID1");
            DropColumn("dbo.LugarViaje", "Encomienda_EncomiendaID1");
            DropColumn("dbo.LugarViaje", "Transporte_TransporteID");
            DropColumn("dbo.LugarViaje", "TipoLugar_TipoLugarID");
            DropColumn("dbo.LugarViaje", "Encomienda_EncomiendaID");
            DropColumn("dbo.LugarViaje", "EncomiendaID");
            DropColumn("dbo.LugarViaje", "TransporteID");
            DropColumn("dbo.LugarViaje", "TiempoEstimado");
            DropColumn("dbo.LugarViaje", "Descripcion");
            DropColumn("dbo.LugarViaje", "TipoLugarID");
            DropColumn("dbo.Evento", "Venta_VentaID1");
            DropColumn("dbo.Evento", "Venta_VentaID");
            DropColumn("dbo.Evento", "Transporte_TransporteID1");
            DropColumn("dbo.Evento", "Transporte_TransporteID");
            DropColumn("dbo.Tripulacion", "TipoTripulacion_TipoTripulacionID");
            DropColumn("dbo.Tripulacion", "Bus1_BusID");
            DropColumn("dbo.Tripulacion", "Apellido");
            DropColumn("dbo.Tripulacion", "Nombre");
            DropColumn("dbo.Transporte", "TipoViaje_TipoViajeID");
            DropColumn("dbo.Transporte", "LugarViaje_LugarViajeID");
            DropColumn("dbo.Transporte", "Cliente_ClienteID");
            DropColumn("dbo.Transporte", "Bus2_BusID");
            DropColumn("dbo.Transporte", "Bus_BusID");
            DropColumn("dbo.Transporte", "ClienteID");
            DropColumn("dbo.Transporte", "TipoViajeID");
            DropColumn("dbo.Transporte", "LugarViajeID");
            DropColumn("dbo.Encomienda", "Bus_BusID1");
            DropColumn("dbo.Encomienda", "LugarViaje_LugarViajeID");
            DropColumn("dbo.Encomienda", "Bust_BusID");
            DropColumn("dbo.Encomienda", "BusID");
            DropColumn("dbo.Encomienda", "Tarea");
            DropColumn("dbo.Encomienda", "Beneficiario");
            DropColumn("dbo.Encomienda", "LugarViajeID");
            DropColumn("dbo.Venta", "TipoPago_TipoPagoID");
            DropColumn("dbo.Venta", "TipoComprobante_TipoComprobanteID");
            DropColumn("dbo.Venta", "Servicio_ServicioID");
            DropColumn("dbo.Venta", "Cliente_ClienteID");
            DropColumn("dbo.Venta", "Administrativo_EmpleadoID");
            DropColumn("dbo.Venta", "Observacion");
            DropColumn("dbo.Venta", "costo");
            DropColumn("dbo.Venta", "ServicioID");
            DropColumn("dbo.Venta", "TipoPagoID");
            DropColumn("dbo.Venta", "TipoComprobanteID");
            DropColumn("dbo.Venta", "AdministrativoID");
            DropColumn("dbo.Venta", "ClienteID");
            DropColumn("dbo.Empleado", "LaborSocial");
            DropColumn("dbo.Empleado", "DNI");
            DropColumn("dbo.Administrativo", "Venta_VentaID1");
            DropColumn("dbo.Administrativo", "Venta_VentaID");
            CreateIndex("dbo.Administrativo", "VentaID");
            CreateIndex("dbo.Evento", "TransporteID");
            CreateIndex("dbo.Evento", "VentaID");
            AddForeignKey("dbo.Evento", "VentaID", "dbo.Venta", "VentaID", cascadeDelete: true);
            AddForeignKey("dbo.Evento", "TransporteID", "dbo.Transporte", "TransporteID", cascadeDelete: true);
            AddForeignKey("dbo.Encomienda", "Bus_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Administrativo", "VentaID", "dbo.Venta", "VentaID", cascadeDelete: true);
        }
    }
}
