// <auto-generated />
namespace _2015147463_PER.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PriceAdded5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriceAdded5));
        
        string IMigrationMetadata.Id
        {
            get { return "201705150238555_PriceAdded5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
