namespace _2015147463_PER.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PriceAdded14 : DbMigration
    {
        public override void Up()
        {
            DropForeignKey("dbo.Administrativo", "Venta_VentaID1", "dbo.Venta");
            DropForeignKey("dbo.Administrativo", "Venta_VentaID", "dbo.Venta");
            DropForeignKey("dbo.Evento", "Venta_VentaID1", "dbo.Venta");
            DropForeignKey("dbo.Servicio", "Venta_VentaID1", "dbo.Venta");
            DropForeignKey("dbo.TipoComprobante", "Venta_VentaID1", "dbo.Venta");
            DropForeignKey("dbo.TipoPago", "Venta_VentaID1", "dbo.Venta");
            DropForeignKey("dbo.Evento", "Venta_VentaID", "dbo.Venta");
            DropForeignKey("dbo.Encomienda", "Bus_BusID1", "dbo.Bus");
            DropForeignKey("dbo.Encomienda", "Bust_BusID", "dbo.Bus");
            DropForeignKey("dbo.TipoLugar", "LugarViaje_LugarViajeID1", "dbo.LugarViaje");
            DropForeignKey("dbo.TipoLugar", "LugarViaje_LugarViajeID", "dbo.LugarViaje");
            DropForeignKey("dbo.TipoTripulacion", "Tripulacion_TripulacionID1", "dbo.Tripulacion");
            DropForeignKey("dbo.TipoTripulacion", "Tripulacion_TripulacionID", "dbo.Tripulacion");
            DropForeignKey("dbo.Servicio", "Venta_VentaID", "dbo.Venta");
            DropForeignKey("dbo.TipoComprobante", "Venta_VentaID", "dbo.Venta");
            DropForeignKey("dbo.TipoPago", "Venta_VentaID", "dbo.Venta");
            DropForeignKey("dbo.LugarViaje", "Transporte_TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.Bus", "Transporte1_TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.Evento", "Transporte_TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.LugarViaje", "Transporte_TransporteID1", "dbo.Transporte");
            DropForeignKey("dbo.TipoViaje", "Transporte_TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.TipoViaje", "Transporte_TransporteID1", "dbo.Transporte");
            DropForeignKey("dbo.Evento", "Transporte_TransporteID1", "dbo.Transporte");
            DropForeignKey("dbo.Encomienda", "Bus_BusID", "dbo.Bus");
            DropForeignKey("dbo.Tripulacion", "Bus1_BusID", "dbo.Bus");
            DropForeignKey("dbo.Transporte", "Bus_BusID", "dbo.Bus");
            DropForeignKey("dbo.Transporte", "Bus2_BusID", "dbo.Bus");
            DropForeignKey("dbo.LugarViaje", "Encomienda_EncomiendaID", "dbo.Encomienda");
            DropForeignKey("dbo.LugarViaje", "Encomienda_EncomiendaID1", "dbo.Encomienda");
            DropIndex("dbo.Evento", new[] { "Transporte_TransporteID" });
            DropIndex("dbo.Evento", new[] { "Transporte_TransporteID1" });
            DropIndex("dbo.Evento", new[] { "Venta_VentaID" });
            DropIndex("dbo.Evento", new[] { "Venta_VentaID1" });
            DropIndex("dbo.Transporte", new[] { "Bus2_BusID" });
            DropIndex("dbo.Bus", new[] { "Transporte1_TransporteID" });
            DropIndex("dbo.Encomienda", new[] { "Bust_BusID" });
            DropIndex("dbo.Encomienda", new[] { "Bus_BusID1" });
            DropIndex("dbo.LugarViaje", new[] { "Encomienda_EncomiendaID" });
            DropIndex("dbo.LugarViaje", new[] { "Transporte_TransporteID" });
            DropIndex("dbo.LugarViaje", new[] { "Encomienda_EncomiendaID1" });
            DropIndex("dbo.LugarViaje", new[] { "Transporte_TransporteID1" });
            DropIndex("dbo.TipoLugar", new[] { "LugarViaje_LugarViajeID" });
            DropIndex("dbo.TipoLugar", new[] { "LugarViaje_LugarViajeID1" });
            DropIndex("dbo.TipoTripulacion", new[] { "Tripulacion_TripulacionID" });
            DropIndex("dbo.TipoTripulacion", new[] { "Tripulacion_TripulacionID1" });
            DropIndex("dbo.TipoViaje", new[] { "Transporte_TransporteID" });
            DropIndex("dbo.TipoViaje", new[] { "Transporte_TransporteID1" });
            DropIndex("dbo.Servicio", new[] { "Venta_VentaID" });
            DropIndex("dbo.Servicio", new[] { "Venta_VentaID1" });
            DropIndex("dbo.TipoComprobante", new[] { "Venta_VentaID" });
            DropIndex("dbo.TipoComprobante", new[] { "Venta_VentaID1" });
            DropIndex("dbo.TipoPago", new[] { "Venta_VentaID" });
            DropIndex("dbo.TipoPago", new[] { "Venta_VentaID1" });
            DropIndex("dbo.Administrativo", new[] { "Venta_VentaID" });
            DropIndex("dbo.Administrativo", new[] { "Venta_VentaID1" });
            DropColumn("dbo.Administrativo", "VentaID");
            DropColumn("dbo.Administrativo", "VentaID");
            DropColumn("dbo.Evento", "VentaID");
            DropColumn("dbo.Evento", "TransporteID");
            DropColumn("dbo.Evento", "VentaID");
            DropColumn("dbo.Evento", "TransporteID");
            DropColumn("dbo.Bus", "BusID");
            DropColumn("dbo.Bus", "BusID");
            DropColumn("dbo.Encomienda", "BusID");
            DropColumn("dbo.Encomienda", "BusID");
            DropColumn("dbo.LugarViaje", "TransporteID");
            DropColumn("dbo.LugarViaje", "EncomiendaID");
            DropColumn("dbo.LugarViaje", "EncomiendaID");
            DropColumn("dbo.LugarViaje", "TransporteID");
            DropColumn("dbo.TipoLugar", "LugarViajeID");
            DropColumn("dbo.TipoLugar", "LugarViajeID");
            DropColumn("dbo.TipoTripulacion", "TripulacionID");
            DropColumn("dbo.TipoTripulacion", "TripulacionID");
            DropColumn("dbo.TipoViaje", "TransporteID");
            DropColumn("dbo.TipoViaje", "TransporteID");
            DropColumn("dbo.TipoComprobante", "VentaID");
            DropColumn("dbo.TipoComprobante", "VentaID");
            DropColumn("dbo.TipoPago", "VentaID");
            DropColumn("dbo.TipoPago", "VentaID");
            DropColumn("dbo.Servicio", "VentaID");
            DropColumn("dbo.Servicio", "VentaID");
            RenameColumn(table: "dbo.Administrativo", name: "Venta_VentaID1", newName: "VentaID");
            RenameColumn(table: "dbo.Administrativo", name: "Venta_VentaID", newName: "VentaID");
            RenameColumn(table: "dbo.Evento", name: "Venta_VentaID1", newName: "VentaID");
            RenameColumn(table: "dbo.Servicio", name: "Venta_VentaID1", newName: "VentaID");
            RenameColumn(table: "dbo.TipoComprobante", name: "Venta_VentaID1", newName: "VentaID");
            RenameColumn(table: "dbo.TipoPago", name: "Venta_VentaID1", newName: "VentaID");
            RenameColumn(table: "dbo.Evento", name: "Transporte_TransporteID1", newName: "TransporteID");
            RenameColumn(table: "dbo.Evento", name: "Venta_VentaID", newName: "VentaID");
            RenameColumn(table: "dbo.Bus", name: "Bus2_BusID", newName: "BusID");
            RenameColumn(table: "dbo.Evento", name: "Transporte_TransporteID", newName: "TransporteID");
            RenameColumn(table: "dbo.LugarViaje", name: "Transporte_TransporteID1", newName: "TransporteID");
            RenameColumn(table: "dbo.TipoViaje", name: "Transporte_TransporteID1", newName: "TransporteID");
            RenameColumn(table: "dbo.Encomienda", name: "Bus_BusID1", newName: "BusID");
            RenameColumn(table: "dbo.Bus", name: "Transporte1_TransporteID", newName: "BusID");
            RenameColumn(table: "dbo.Encomienda", name: "Bust_BusID", newName: "BusID");
            RenameColumn(table: "dbo.LugarViaje", name: "Encomienda_EncomiendaID1", newName: "EncomiendaID");
            RenameColumn(table: "dbo.LugarViaje", name: "Encomienda_EncomiendaID", newName: "EncomiendaID");
            RenameColumn(table: "dbo.TipoLugar", name: "LugarViaje_LugarViajeID1", newName: "LugarViajeID");
            RenameColumn(table: "dbo.LugarViaje", name: "Transporte_TransporteID", newName: "TransporteID");
            RenameColumn(table: "dbo.TipoLugar", name: "LugarViaje_LugarViajeID", newName: "LugarViajeID");
            RenameColumn(table: "dbo.TipoTripulacion", name: "Tripulacion_TripulacionID1", newName: "TripulacionID");
            RenameColumn(table: "dbo.TipoTripulacion", name: "Tripulacion_TripulacionID", newName: "TripulacionID");
            RenameColumn(table: "dbo.TipoViaje", name: "Transporte_TransporteID", newName: "TransporteID");
            RenameColumn(table: "dbo.Servicio", name: "Venta_VentaID", newName: "VentaID");
            RenameColumn(table: "dbo.TipoComprobante", name: "Venta_VentaID", newName: "VentaID");
            RenameColumn(table: "dbo.TipoPago", name: "Venta_VentaID", newName: "VentaID");
            DropPrimaryKey("dbo.Transporte");
            DropPrimaryKey("dbo.Bus");
            DropPrimaryKey("dbo.Encomienda");
            AddColumn("dbo.Transporte", "ServicioID", c => c.Int(nullable: false));
            AddColumn("dbo.Encomienda", "ServicioID", c => c.Int(nullable: false));
            AlterColumn("dbo.Administrativo", "VentaID", c => c.Int(nullable: false));
            AlterColumn("dbo.Administrativo", "VentaID", c => c.Int(nullable: false));
            AlterColumn("dbo.Empleado", "DNI", c => c.String(nullable: false));
            AlterColumn("dbo.Empleado", "LaborSocial", c => c.String(nullable: false));
            AlterColumn("dbo.Evento", "TransporteID", c => c.Int(nullable: false));
            AlterColumn("dbo.Evento", "TransporteID", c => c.Int(nullable: false));
            AlterColumn("dbo.Evento", "VentaID", c => c.Int(nullable: false));
            AlterColumn("dbo.Evento", "VentaID", c => c.Int(nullable: false));
            AlterColumn("dbo.Transporte", "TransporteID", c => c.Int(nullable: false));
            AlterColumn("dbo.Bus", "BusID", c => c.Int(nullable: false));
            AlterColumn("dbo.Bus", "BusID", c => c.Int(nullable: false));
            AlterColumn("dbo.Encomienda", "EncomiendaID", c => c.Int(nullable: false));
            AlterColumn("dbo.Encomienda", "BusID", c => c.Int(nullable: false));
            AlterColumn("dbo.Encomienda", "BusID", c => c.Int(nullable: false));
            AlterColumn("dbo.LugarViaje", "EncomiendaID", c => c.Int(nullable: false));
            AlterColumn("dbo.LugarViaje", "TransporteID", c => c.Int(nullable: false));
            AlterColumn("dbo.LugarViaje", "EncomiendaID", c => c.Int(nullable: false));
            AlterColumn("dbo.LugarViaje", "TransporteID", c => c.Int(nullable: false));
            AlterColumn("dbo.TipoLugar", "LugarViajeID", c => c.Int(nullable: false));
            AlterColumn("dbo.TipoLugar", "LugarViajeID", c => c.Int(nullable: false));
            AlterColumn("dbo.TipoTripulacion", "TripulacionID", c => c.Int(nullable: false));
            AlterColumn("dbo.TipoTripulacion", "TripulacionID", c => c.Int(nullable: false));
            AlterColumn("dbo.TipoViaje", "TransporteID", c => c.Int(nullable: false));
            AlterColumn("dbo.TipoViaje", "TransporteID", c => c.Int(nullable: false));
            AlterColumn("dbo.TipoComprobante", "VentaID", c => c.Int(nullable: false));
            AlterColumn("dbo.TipoComprobante", "VentaID", c => c.Int(nullable: false));
            AlterColumn("dbo.TipoPago", "VentaID", c => c.Int(nullable: false));
            AlterColumn("dbo.TipoPago", "VentaID", c => c.Int(nullable: false));
            AlterColumn("dbo.Servicio", "Tipo", c => c.String(nullable: false));
            AlterColumn("dbo.Servicio", "DescripcionServicio", c => c.String(nullable: false));
            AlterColumn("dbo.Servicio", "VentaID", c => c.Int(nullable: false));
            AlterColumn("dbo.Servicio", "VentaID", c => c.Int(nullable: false));
            AddPrimaryKey("dbo.Transporte", "ServicioID");
            AddPrimaryKey("dbo.Bus", "BusID");
            AddPrimaryKey("dbo.Encomienda", "ServicioID");
            CreateIndex("dbo.Evento", "VentaID");
            CreateIndex("dbo.Evento", "TransporteID");
            CreateIndex("dbo.Servicio", "VentaID");
            CreateIndex("dbo.Bus", "BusID");
            CreateIndex("dbo.LugarViaje", "TransporteID");
            CreateIndex("dbo.LugarViaje", "EncomiendaID");
            CreateIndex("dbo.TipoLugar", "LugarViajeID");
            CreateIndex("dbo.TipoTripulacion", "TripulacionID");
            CreateIndex("dbo.TipoViaje", "TransporteID");
            CreateIndex("dbo.TipoComprobante", "VentaID");
            CreateIndex("dbo.TipoPago", "VentaID");
            CreateIndex("dbo.Administrativo", "VentaID");
            CreateIndex("dbo.Encomienda", "ServicioID");
            CreateIndex("dbo.Encomienda", "BusID");
            CreateIndex("dbo.Transporte", "ServicioID");
            AddForeignKey("dbo.Encomienda", "ServicioID", "dbo.Servicio", "ServicioID");
            AddForeignKey("dbo.Transporte", "ServicioID", "dbo.Servicio", "ServicioID");
            AddForeignKey("dbo.Administrativo", "VentaID", "dbo.Venta", "VentaID", cascadeDelete: true);
            AddForeignKey("dbo.Evento", "VentaID", "dbo.Venta", "VentaID", cascadeDelete: true);
            AddForeignKey("dbo.Servicio", "VentaID", "dbo.Venta", "VentaID", cascadeDelete: true);
            AddForeignKey("dbo.TipoComprobante", "VentaID", "dbo.Venta", "VentaID", cascadeDelete: true);
            AddForeignKey("dbo.TipoPago", "VentaID", "dbo.Venta", "VentaID", cascadeDelete: true);
            AddForeignKey("dbo.Encomienda", "BusID", "dbo.Bus", "BusID", cascadeDelete: true);
            AddForeignKey("dbo.TipoLugar", "LugarViajeID", "dbo.LugarViaje", "LugarViajeID", cascadeDelete: true);
            AddForeignKey("dbo.TipoTripulacion", "TripulacionID", "dbo.Tripulacion", "TripulacionID", cascadeDelete: true);
            AddForeignKey("dbo.Bus", "BusID", "dbo.Transporte", "ServicioID");
            AddForeignKey("dbo.Evento", "TransporteID", "dbo.Transporte", "ServicioID");
            AddForeignKey("dbo.LugarViaje", "TransporteID", "dbo.Transporte", "ServicioID");
            AddForeignKey("dbo.TipoViaje", "TransporteID", "dbo.Transporte", "ServicioID");
            AddForeignKey("dbo.Tripulacion", "Bus1_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Encomienda", "Bus_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Transporte", "Bus_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.LugarViaje", "EncomiendaID", "dbo.Encomienda", "ServicioID");
            DropColumn("dbo.Transporte", "Bus2_BusID");
        }
        
        public override void Down()
        {
            AddColumn("dbo.Transporte", "Bus2_BusID", c => c.Int());
            DropForeignKey("dbo.LugarViaje", "EncomiendaID", "dbo.Encomienda");
            DropForeignKey("dbo.Transporte", "Bus_BusID", "dbo.Bus");
            DropForeignKey("dbo.Encomienda", "Bus_BusID", "dbo.Bus");
            DropForeignKey("dbo.Tripulacion", "Bus1_BusID", "dbo.Bus");
            DropForeignKey("dbo.TipoViaje", "TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.LugarViaje", "TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.Evento", "TransporteID", "dbo.Transporte");
            DropForeignKey("dbo.Bus", "BusID", "dbo.Transporte");
            DropForeignKey("dbo.TipoTripulacion", "TripulacionID", "dbo.Tripulacion");
            DropForeignKey("dbo.TipoLugar", "LugarViajeID", "dbo.LugarViaje");
            DropForeignKey("dbo.Encomienda", "BusID", "dbo.Bus");
            DropForeignKey("dbo.TipoPago", "VentaID", "dbo.Venta");
            DropForeignKey("dbo.TipoComprobante", "VentaID", "dbo.Venta");
            DropForeignKey("dbo.Servicio", "VentaID", "dbo.Venta");
            DropForeignKey("dbo.Evento", "VentaID", "dbo.Venta");
            DropForeignKey("dbo.Administrativo", "VentaID", "dbo.Venta");
            DropForeignKey("dbo.Transporte", "ServicioID", "dbo.Servicio");
            DropForeignKey("dbo.Encomienda", "ServicioID", "dbo.Servicio");
            DropIndex("dbo.Transporte", new[] { "ServicioID" });
            DropIndex("dbo.Encomienda", new[] { "BusID" });
            DropIndex("dbo.Encomienda", new[] { "ServicioID" });
            DropIndex("dbo.Administrativo", new[] { "VentaID" });
            DropIndex("dbo.TipoPago", new[] { "VentaID" });
            DropIndex("dbo.TipoComprobante", new[] { "VentaID" });
            DropIndex("dbo.TipoViaje", new[] { "TransporteID" });
            DropIndex("dbo.TipoTripulacion", new[] { "TripulacionID" });
            DropIndex("dbo.TipoLugar", new[] { "LugarViajeID" });
            DropIndex("dbo.LugarViaje", new[] { "EncomiendaID" });
            DropIndex("dbo.LugarViaje", new[] { "TransporteID" });
            DropIndex("dbo.Bus", new[] { "BusID" });
            DropIndex("dbo.Servicio", new[] { "VentaID" });
            DropIndex("dbo.Evento", new[] { "TransporteID" });
            DropIndex("dbo.Evento", new[] { "VentaID" });
            DropPrimaryKey("dbo.Encomienda");
            DropPrimaryKey("dbo.Bus");
            DropPrimaryKey("dbo.Transporte");
            AlterColumn("dbo.Servicio", "VentaID", c => c.Int());
            AlterColumn("dbo.Servicio", "VentaID", c => c.Int());
            AlterColumn("dbo.Servicio", "DescripcionServicio", c => c.String());
            AlterColumn("dbo.Servicio", "Tipo", c => c.String());
            AlterColumn("dbo.TipoPago", "VentaID", c => c.Int());
            AlterColumn("dbo.TipoPago", "VentaID", c => c.Int());
            AlterColumn("dbo.TipoComprobante", "VentaID", c => c.Int());
            AlterColumn("dbo.TipoComprobante", "VentaID", c => c.Int());
            AlterColumn("dbo.TipoViaje", "TransporteID", c => c.Int());
            AlterColumn("dbo.TipoViaje", "TransporteID", c => c.Int());
            AlterColumn("dbo.TipoTripulacion", "TripulacionID", c => c.Int());
            AlterColumn("dbo.TipoTripulacion", "TripulacionID", c => c.Int());
            AlterColumn("dbo.TipoLugar", "LugarViajeID", c => c.Int());
            AlterColumn("dbo.TipoLugar", "LugarViajeID", c => c.Int());
            AlterColumn("dbo.LugarViaje", "TransporteID", c => c.Int());
            AlterColumn("dbo.LugarViaje", "EncomiendaID", c => c.Int());
            AlterColumn("dbo.LugarViaje", "TransporteID", c => c.Int());
            AlterColumn("dbo.LugarViaje", "EncomiendaID", c => c.Int());
            AlterColumn("dbo.Encomienda", "BusID", c => c.Int());
            AlterColumn("dbo.Encomienda", "BusID", c => c.Int());
            AlterColumn("dbo.Encomienda", "EncomiendaID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Bus", "BusID", c => c.Int());
            AlterColumn("dbo.Bus", "BusID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Transporte", "TransporteID", c => c.Int(nullable: false, identity: true));
            AlterColumn("dbo.Evento", "VentaID", c => c.Int());
            AlterColumn("dbo.Evento", "VentaID", c => c.Int());
            AlterColumn("dbo.Evento", "TransporteID", c => c.Int());
            AlterColumn("dbo.Evento", "TransporteID", c => c.Int());
            AlterColumn("dbo.Empleado", "LaborSocial", c => c.String());
            AlterColumn("dbo.Empleado", "DNI", c => c.String());
            AlterColumn("dbo.Administrativo", "VentaID", c => c.Int());
            AlterColumn("dbo.Administrativo", "VentaID", c => c.Int());
            DropColumn("dbo.Encomienda", "ServicioID");
            DropColumn("dbo.Transporte", "ServicioID");
            AddPrimaryKey("dbo.Encomienda", "EncomiendaID");
            AddPrimaryKey("dbo.Bus", "BusID");
            AddPrimaryKey("dbo.Transporte", "TransporteID");
            RenameColumn(table: "dbo.TipoPago", name: "VentaID", newName: "Venta_VentaID");
            RenameColumn(table: "dbo.TipoComprobante", name: "VentaID", newName: "Venta_VentaID");
            RenameColumn(table: "dbo.Servicio", name: "VentaID", newName: "Venta_VentaID");
            RenameColumn(table: "dbo.TipoViaje", name: "TransporteID", newName: "Transporte_TransporteID");
            RenameColumn(table: "dbo.TipoTripulacion", name: "TripulacionID", newName: "Tripulacion_TripulacionID");
            RenameColumn(table: "dbo.TipoTripulacion", name: "TripulacionID", newName: "Tripulacion_TripulacionID1");
            RenameColumn(table: "dbo.TipoLugar", name: "LugarViajeID", newName: "LugarViaje_LugarViajeID");
            RenameColumn(table: "dbo.LugarViaje", name: "TransporteID", newName: "Transporte_TransporteID");
            RenameColumn(table: "dbo.TipoLugar", name: "LugarViajeID", newName: "LugarViaje_LugarViajeID1");
            RenameColumn(table: "dbo.LugarViaje", name: "EncomiendaID", newName: "Encomienda_EncomiendaID");
            RenameColumn(table: "dbo.LugarViaje", name: "EncomiendaID", newName: "Encomienda_EncomiendaID1");
            RenameColumn(table: "dbo.Encomienda", name: "BusID", newName: "Bust_BusID");
            RenameColumn(table: "dbo.Bus", name: "BusID", newName: "Transporte1_TransporteID");
            RenameColumn(table: "dbo.Encomienda", name: "BusID", newName: "Bus_BusID1");
            RenameColumn(table: "dbo.TipoViaje", name: "TransporteID", newName: "Transporte_TransporteID1");
            RenameColumn(table: "dbo.LugarViaje", name: "TransporteID", newName: "Transporte_TransporteID1");
            RenameColumn(table: "dbo.Evento", name: "TransporteID", newName: "Transporte_TransporteID");
            RenameColumn(table: "dbo.Bus", name: "BusID", newName: "Bus2_BusID");
            RenameColumn(table: "dbo.Evento", name: "VentaID", newName: "Venta_VentaID");
            RenameColumn(table: "dbo.Evento", name: "TransporteID", newName: "Transporte_TransporteID1");
            RenameColumn(table: "dbo.TipoPago", name: "VentaID", newName: "Venta_VentaID1");
            RenameColumn(table: "dbo.TipoComprobante", name: "VentaID", newName: "Venta_VentaID1");
            RenameColumn(table: "dbo.Servicio", name: "VentaID", newName: "Venta_VentaID1");
            RenameColumn(table: "dbo.Evento", name: "VentaID", newName: "Venta_VentaID1");
            RenameColumn(table: "dbo.Administrativo", name: "VentaID", newName: "Venta_VentaID");
            RenameColumn(table: "dbo.Administrativo", name: "VentaID", newName: "Venta_VentaID1");
            AddColumn("dbo.Servicio", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.Servicio", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoPago", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoPago", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoComprobante", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoComprobante", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoViaje", "TransporteID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoViaje", "TransporteID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoTripulacion", "TripulacionID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoTripulacion", "TripulacionID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoLugar", "LugarViajeID", c => c.Int(nullable: false));
            AddColumn("dbo.TipoLugar", "LugarViajeID", c => c.Int(nullable: false));
            AddColumn("dbo.LugarViaje", "TransporteID", c => c.Int(nullable: false));
            AddColumn("dbo.LugarViaje", "EncomiendaID", c => c.Int(nullable: false));
            AddColumn("dbo.LugarViaje", "EncomiendaID", c => c.Int(nullable: false));
            AddColumn("dbo.LugarViaje", "TransporteID", c => c.Int(nullable: false));
            AddColumn("dbo.Encomienda", "BusID", c => c.Int(nullable: false));
            AddColumn("dbo.Encomienda", "BusID", c => c.Int(nullable: false));
            AddColumn("dbo.Bus", "BusID", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Bus", "BusID", c => c.Int(nullable: false, identity: true));
            AddColumn("dbo.Evento", "TransporteID", c => c.Int(nullable: false));
            AddColumn("dbo.Evento", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.Evento", "TransporteID", c => c.Int(nullable: false));
            AddColumn("dbo.Evento", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.Administrativo", "VentaID", c => c.Int(nullable: false));
            AddColumn("dbo.Administrativo", "VentaID", c => c.Int(nullable: false));
            CreateIndex("dbo.Administrativo", "Venta_VentaID1");
            CreateIndex("dbo.Administrativo", "Venta_VentaID");
            CreateIndex("dbo.TipoPago", "Venta_VentaID1");
            CreateIndex("dbo.TipoPago", "Venta_VentaID");
            CreateIndex("dbo.TipoComprobante", "Venta_VentaID1");
            CreateIndex("dbo.TipoComprobante", "Venta_VentaID");
            CreateIndex("dbo.Servicio", "Venta_VentaID1");
            CreateIndex("dbo.Servicio", "Venta_VentaID");
            CreateIndex("dbo.TipoViaje", "Transporte_TransporteID1");
            CreateIndex("dbo.TipoViaje", "Transporte_TransporteID");
            CreateIndex("dbo.TipoTripulacion", "Tripulacion_TripulacionID1");
            CreateIndex("dbo.TipoTripulacion", "Tripulacion_TripulacionID");
            CreateIndex("dbo.TipoLugar", "LugarViaje_LugarViajeID1");
            CreateIndex("dbo.TipoLugar", "LugarViaje_LugarViajeID");
            CreateIndex("dbo.LugarViaje", "Transporte_TransporteID1");
            CreateIndex("dbo.LugarViaje", "Encomienda_EncomiendaID1");
            CreateIndex("dbo.LugarViaje", "Transporte_TransporteID");
            CreateIndex("dbo.LugarViaje", "Encomienda_EncomiendaID");
            CreateIndex("dbo.Encomienda", "Bus_BusID1");
            CreateIndex("dbo.Encomienda", "Bust_BusID");
            CreateIndex("dbo.Bus", "Transporte1_TransporteID");
            CreateIndex("dbo.Transporte", "Bus2_BusID");
            CreateIndex("dbo.Evento", "Venta_VentaID1");
            CreateIndex("dbo.Evento", "Venta_VentaID");
            CreateIndex("dbo.Evento", "Transporte_TransporteID1");
            CreateIndex("dbo.Evento", "Transporte_TransporteID");
            AddForeignKey("dbo.LugarViaje", "Encomienda_EncomiendaID1", "dbo.Encomienda", "EncomiendaID");
            AddForeignKey("dbo.LugarViaje", "Encomienda_EncomiendaID", "dbo.Encomienda", "EncomiendaID");
            AddForeignKey("dbo.Transporte", "Bus2_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Transporte", "Bus_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Tripulacion", "Bus1_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Encomienda", "Bus_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Evento", "Transporte_TransporteID1", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.TipoViaje", "Transporte_TransporteID1", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.TipoViaje", "Transporte_TransporteID", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.LugarViaje", "Transporte_TransporteID1", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.Evento", "Transporte_TransporteID", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.Bus", "Transporte1_TransporteID", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.LugarViaje", "Transporte_TransporteID", "dbo.Transporte", "TransporteID");
            AddForeignKey("dbo.TipoPago", "Venta_VentaID", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.TipoComprobante", "Venta_VentaID", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Servicio", "Venta_VentaID", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.TipoTripulacion", "Tripulacion_TripulacionID", "dbo.Tripulacion", "TripulacionID");
            AddForeignKey("dbo.TipoTripulacion", "Tripulacion_TripulacionID1", "dbo.Tripulacion", "TripulacionID");
            AddForeignKey("dbo.TipoLugar", "LugarViaje_LugarViajeID", "dbo.LugarViaje", "LugarViajeID");
            AddForeignKey("dbo.TipoLugar", "LugarViaje_LugarViajeID1", "dbo.LugarViaje", "LugarViajeID");
            AddForeignKey("dbo.Encomienda", "Bust_BusID", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Encomienda", "Bus_BusID1", "dbo.Bus", "BusID");
            AddForeignKey("dbo.Evento", "Venta_VentaID", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.TipoPago", "Venta_VentaID1", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.TipoComprobante", "Venta_VentaID1", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Servicio", "Venta_VentaID1", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Evento", "Venta_VentaID1", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Administrativo", "Venta_VentaID", "dbo.Venta", "VentaID");
            AddForeignKey("dbo.Administrativo", "Venta_VentaID1", "dbo.Venta", "VentaID");
        }
    }
}
